AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: SAM Template for Deployment and Local Testing with Docker

Globals:
  Api:
    Cors:
      AllowMethods: "'GET,POST,DELETE,PATCH,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"
  Function:
    Runtime: provided.al2023
    MemorySize: 128
    Timeout: 30
    Environment:
      Variables:
        STAGE: !Ref Stage
        DYNAMODB_ENDPOINT: ""

Parameters:
  Stage:
    Type: String
    Default: "local" 
    AllowedValues:
      - dev
      - local
      - prod
  AppName:
    Type: String
    Default: "serverlessTemplate" # Put app name here in camel case
  AppNameDashed:
    Type: String
    Default: "serverless-template" # Put app name here in kebab case

Resources: 

  InvalidatePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${AppName}-${Stage}-InvalidatePolicy"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - cloudfront:CreateInvalidation
            Resource: "*"

  DynamoDBPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${AppName}-${Stage}-DynamoDBPolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
              - dynamodb:Query
            Resource: !GetAtt SomethingsTable.Arn

  CloudWatchLogsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${AppName}-${Stage}-CloudWatchLogsPolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: "arn:aws:logs:*:*:*"

  InvalidateRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AppName}-${Stage}-invalidateRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Ref InvalidatePolicy
        - !Ref CloudWatchLogsPolicy

  LambdaApiExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Ref DynamoDBPolicy
        - !Ref CloudWatchLogsPolicy

  InvalidationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AppName}-${Stage}-invalidationControl"
      Handler: bootstrap
      CodeUri: bin/invalidationControl.zip
      Role: !GetAtt InvalidateRole.Arn
      Environment:
        Variables:
          DISTRIBUTION_ID: !ImportValue CloudFrontDistributionId 
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref FrontendBucket   
            Events: s3:ObjectCreated:*

  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${AppName}-${Stage}-api"
      StageName: !Ref Stage
      AccessLogSetting:
        DestinationArn: !GetAtt ApiLogGroup.Arn
        Format: '{ "requestId":"$context.requestId", "ip": "$context.identity.sourceIp", "caller": "$context.identity.caller", "user": "$context.identity.user", "requestTime": "$context.requestTime", "httpMethod": "$context.httpMethod", "resourcePath": "$context.resourcePath", "status": "$context.status", "protocol": "$context.protocol", "responseLength": "$context.responseLength" }'
      MethodSettings:
        - DataTraceEnabled: true
          HttpMethod: "*"
          LoggingLevel: INFO
          ResourcePath: "/*"
          MetricsEnabled: true

  ApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/apigateway/${AppName}-${Stage}-api"
      RetentionInDays: 7

  GetSomethingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AppName}-${Stage}-getSomethingFunction"
      Handler: bootstrap
      CodeUri: bin/getSomething.zip
      Role: !GetAtt LambdaApiExecutionRole.Arn
      Events:
        GetSomethingApi:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /api/something/{id}
            Method: get

  PostSomethingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AppName}-${Stage}-postSomethingFunction"
      Handler: bootstrap
      CodeUri: bin/postSomething.zip
      Role: !GetAtt LambdaApiExecutionRole.Arn
      Events:
        PostSomethingApi:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /api/something
            Method: post

  PatchSomethingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AppName}-${Stage}-patchSomethingFunction"
      Handler: bootstrap
      CodeUri: bin/patchSomething.zip
      Role: !GetAtt LambdaApiExecutionRole.Arn
      Events:
        PatchSomethingApi:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /api/something
            Method: patch

  DeleteSomethingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AppName}-${Stage}-deleteSomethingFunction"
      Handler: bootstrap
      CodeUri: bin/deleteSomething.zip
      Role: !GetAtt LambdaApiExecutionRole.Arn
      Events:
        DeleteSomethingApi:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /api/something/{id}
            Method: delete

  SomethingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AppName}-${Stage}-somethingsTable"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AppNameDashed}-${Stage}-frontend"
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      Tags:
        - Key: Environment
          Value: !Ref Stage

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${FrontendBucket.Arn}/*"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - DomainName: !GetAtt FrontendBucket.DomainName
            Id: S3Origin
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:827183242253:certificate/9790a1b0-99d3-4fbb-a45e-2de60e2defb2
          SslSupportMethod: sni-only
        DefaultRootObject: index.html
        PriceClass: PriceClass_100
        Aliases:
          - !Sub "${AppNameDashed}-${Stage}.marneinnovationcenter.com"

  RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: "marneinnovationcenter.com."
      Name: !Sub "${AppNameDashed}-${Stage}.marneinnovationcenter.com."
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  ApiUrl:
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/"
    Description: "API Gateway endpoint URL"
  WebsiteURL:
    Value: !Sub "https://${AppNameDashed}-${Stage}.marneinnovationcenter.com"
    Description: "URL for the static website hosted on S3 and served via CloudFront"
  CloudFrontDistributionId:
    Value: !Ref CloudFrontDistribution
    Description: "CloudFront Distribution ID"
    Export:
      Name: "CloudFrontDistributionId"
  CloudFrontDomainName:
    Value: !GetAtt CloudFrontDistribution.DomainName
    Description: "Domain name for the CloudFront distribution"
  Route53Record:
    Value: !Ref RecordSet
    Description: "Route 53 record for the subdomain ${AppNameDashed}-${Stage}.marneinnovationcenter.com"
